//#############SECTION EEPROM STORAGE ADDRESSES#############
#define EEPROM_ADDRESS_OFFSET_H 1
#define EEPROM_ADDRESS_OFFSET_V 2

#define EEPROM_ADDRESS_OFFSET_H_negativ 3
#define EEPROM_ADDRESS_OFFSET_V_negativ 4